In [ ]:
import pandas as pd
import numpy as np
import seaborn as sns

In [ ]:
df = pd.read_csv('/content/sample_data/fifa_s2.csv')

**1. Скачайте датасет fifаs2.сsv. Проанализируйте его и определите, какие данные являются неполными. Удалите
ненужные колонки и недостающие значения.**

In [ ]:
df.shape

(2399, 18)

In [59]:
df.describe()

,ID,Age,Overall,Potential,Value,Wage,International Reputation,Skill Moves,Joined,Height,Weight,Release Clause
count,2399.000000,2399.000000,2399.000000,2399.000000,2142.000000,2399.000000,2389.000000,2393.000000,2399.000000,2399.000000,2399.000000,2396.000000
mean,212033.680700,25.213005,69.115048,74.115048,5980.873016,24.178825,1.308497,2.469703,2016.145894,5.955300,166.802782,10690.033498
std,30549.399068,4.633622,8.060195,7.190957,11963.420681,49.552098,0.687175,0.844531,2.085829,0.219249,15.241015,21780.029323
min,1179.000000,16.000000,47.000000,48.000000,20.000000,0.000000,1.000000,1.000000,2000.000000,5.250000,121.000000,35.000000
25%,195105.000000,22.000000,64.000000,69.000000,500.000000,1.000000,1.000000,2.000000,2016.000000,5.833333,154.000000,1100.000000
50%,218745.000000,25.000000,69.000000,74.000000,1100.000000,5.000000,1.000000,2.000000,2017.000000,6.000000,165.000000,3800.000000
75%,234576.000000,29.000000,74.000000,79.000000,6000.000000,22.000000,1.000000,3.000000,2018.000000,6.083333,176.000000,7500.000000
max,246608.000000,44.000000,94.000000,95.000000,118500.000000,565.000000,5.000000,5.000000,2018.000000,6.583333,214.000000,228100.000000

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2399 entries, 0 to 2398
Data columns (total 18 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   ID                        2399 non-null   int64
 1   Name                      2399 non-null   object
 2   Age                       2399 non-null   int64
 3   Nationality               2392 non-null   object
 4   Overall                   2399 non-null   int64
 5   Potential                 2399 non-null   int64
 6   Club                      2158 non-null   object
 7   Value                     2142 non-null   float64
 8   Wage                      2399 non-null   int64
 9   Preferred Foot            2399 non-null   object
 10  International Reputation  2389 non-null   float64
 11  Skill Moves               2393 non-null   float64
 12  Position                  2378 non-null   object
 13  Joined                    2399 non-null   int64
 14  Contract Valid Until      2126 non-null   object
 15  Height                    2399 non-null   float64
 16  Weight                    2399 non-null   float64
 17  Release Clause            2396 non-null   float64
dtypes: float64(6), int64(6), object(6)
memory usage: 337.5+ KB

In [ ]:
df.isna().sum()/len(df) * 100

ID                           0.000000
Name                         0.000000
Age                          0.000000
Nationality                  0.291788
Overall                      0.000000
Potential                    0.000000
Club                        10.045852
Value                       10.712797
Wage                         0.000000
Preferred Foot               0.000000
International Reputation     0.416840
Skill Moves                  0.250104
Position                     0.875365
Joined                       0.000000
Contract Valid Until        11.379742
Height                       0.000000
Weight                       0.000000
Release Clause               0.125052
dtype: float64

In [ ]:
df.head()

,ID,Name,Age,Nationality,Overall,Potential,Club,Value,Wage,Preferred Foot,International Reputation,Skill Moves,Position,Joined,Contract Valid Until,Height,Weight,Release Clause
0,1179,G. Buffon,40,Italy,88,88,Paris Saint-Germain,4000.0,77,Right,4.0,1.0,GK,2018,01/01/2019,6.333333,203.0,7400.0
1,5479,Casillas,37,Spain,82,82,FC Porto,1500.0,10,Left,4.0,1.0,NaN,2015,01/01/2019,6.083333,185.0,3000.0
2,8205,Braga,35,Portugal,70,70,CD Aves,750.0,5,Right,1.0,3.0,LCM,2017,01/01/2019,5.916667,165.0,1600.0
3,9014,A. Robben,34,Netherlands,84,84,FC Bayern München,15500.0,110,Left,4.0,4.0,RM,2009,01/01/2019,5.916667,176.0,25600.0
4,19521,J. Ibehre,35,England,61,61,Cambridge United,120.0,2,Right,1.0,2.0,ST,2017,01/01/2019,6.333333,203.0,210.0

In [ ]:
df.isna().sum()

ID                            0
Name                          0
Age                           0
Nationality                   7
Overall                       0
Potential                     0
Club                        241
Value                       257
Wage                          0
Preferred Foot                0
International Reputation     10
Skill Moves                   6
Position                     21
Joined                        0
Contract Valid Until        273
Height                        0
Weight                        0
Release Clause                3
dtype: int64

In [ ]:
df[df['Club'].isna()]

,ID,Name,Age,Nationality,Overall,Potential,Club,Value,Wage,Preferred Foot,International Reputation,Skill Moves,Position,Joined,Contract Valid Until,Height,Weight,Release Clause
48,140222,P. Da Silva,38,Paraguay,72,72,NaN,NaN,0,Right,2.0,2.0,RCB,2016,NaN,5.916667,168.0,4585.060806
72,147899,C. Moţi,33,Romania,69,69,NaN,NaN,0,Right,1.0,2.0,LCB,2016,NaN,6.000000,172.0,4585.060806
81,153160,R. Raldes,37,Bolivia,70,70,NaN,NaN,0,Right,1.0,2.0,LB,2016,NaN,5.916667,172.0,4585.060806
84,156092,J. Villar,41,Paraguay,77,77,NaN,NaN,0,Right,2.0,1.0,GK,2016,NaN,5.916667,187.0,4585.060806
89,156713,A. Granqvist,33,Sweden,80,80,NaN,NaN,0,Right,2.0,2.0,LCB,2016,NaN,6.333333,185.0,4585.060806
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2388,246403,B. Caicedo,26,Ecuador,72,75,NaN,NaN,0,Left,1.0,3.0,LB,2016,NaN,5.916667,159.0,4585.060806
2389,246404,J. Cifuente,25,Ecuador,68,70,NaN,NaN,0,Right,1.0,3.0,ST,2016,NaN,5.833333,170.0,4585.060806
2390,246405,B. Angulo,22,Ecuador,71,77,NaN,NaN,0,Right,1.0,3.0,ST,2016,NaN,6.000000,154.0,4585.060806
2391,246406,X. Arreaga,23,Ecuador,66,71,NaN,NaN,0,Right,1.0,2.0,CB,2016,NaN,6.000000,165.0,4585.060806
2392,246407,C. Añez,22,Bolivia,63,68,NaN,NaN,0,Right,1.0,2.0,RB,2016,NaN,5.750000,143.0,4585.060806

In [ ]:
df_new = df.dropna()  # df_1 = df.dropna(subset=(['Club']), axis=0) - удаление пустых строк по столбцу

In [ ]:
df_new.info()

<class 'pandas.core.frame.DataFrame'>
Index: 2075 entries, 0 to 2398
Data columns (total 18 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   ID                        2075 non-null   int64
 1   Name                      2075 non-null   object
 2   Age                       2075 non-null   int64
 3   Nationality               2075 non-null   object
 4   Overall                   2075 non-null   int64
 5   Potential                 2075 non-null   int64
 6   Club                      2075 non-null   object
 7   Value                     2075 non-null   float64
 8   Wage                      2075 non-null   int64
 9   Preferred Foot            2075 non-null   object
 10  International Reputation  2075 non-null   float64
 11  Skill Moves               2075 non-null   float64
 12  Position                  2075 non-null   object
 13  Joined                    2075 non-null   int64
 14  Contract Valid Until      2075 non-null   object
 15  Height                    2075 non-null   float64
 16  Weight                    2075 non-null   float64
 17  Release Clause            2075 non-null   float64
dtypes: float64(6), int64(6), object(6)
memory usage: 308.0+ KB

In [ ]:
df_new.head()

,ID,Name,Age,Nationality,Overall,Potential,Club,Value,Wage,Preferred Foot,International Reputation,Skill Moves,Position,Joined,Contract Valid Until,Height,Weight,Release Clause
0,1179,G. Buffon,40,Italy,88,88,Paris Saint-Germain,4000.0,77,Right,4.0,1.0,GK,2018,01/01/2019,6.333333,203.0,7400.0
2,8205,Braga,35,Portugal,70,70,CD Aves,750.0,5,Right,1.0,3.0,LCM,2017,01/01/2019,5.916667,165.0,1600.0
3,9014,A. Robben,34,Netherlands,84,84,FC Bayern München,15500.0,110,Left,4.0,4.0,RM,2009,01/01/2019,5.916667,176.0,25600.0
4,19521,J. Ibehre,35,England,61,61,Cambridge United,120.0,2,Right,1.0,2.0,ST,2017,01/01/2019,6.333333,203.0,210.0
5,20209,Ricardo Costa,37,Portugal,74,74,CD Tondela,750.0,4,Right,2.0,2.0,LCB,2017,01/01/2019,6.000000,181.0,1600.0

**2. Найдите в датафрейме полные дубликаты и удалите их. Значения могут быть одинаковыми, но написаны по-разному. Например, может отличаться размер регистра (заглавные и строчные буквы). Особое внимание уделить колонке с названиями команд.**

In [ ]:
df_new['Name'] = df_new['Name'].str.lower()
df_new['Nationality'] = df_new['Nationality'].str.lower()
df_new['Club'] = df_new['Club'].str.lower()
df_new['Preferred Foot'] = df_new['Preferred Foot'].str.lower()

<ipython-input-49-23c762ea0b38>:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_new['Name'] = df_new['Name'].str.lower()
<ipython-input-49-23c762ea0b38>:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_new['Nationality'] = df_new['Nationality'].str.lower()
<ipython-input-49-23c762ea0b38>:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_new['Club'] = df_new['Club'].str.lower()
<ipython-input-49-23c762ea0b38>:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_new['Preferred Foot'] = df_new['Preferred Foot'].str.lower()

In [ ]:
df_new.drop(['Potential'], axis=1, inplace=True)

<ipython-input-50-3d3b2e0de746>:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_new.drop(['Potential'], axis=1, inplace=True)

In [ ]:
df_new = df_new.drop_duplicates().reset_index(drop=True)

In [ ]:
df_new.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2073 entries, 0 to 2072
Data columns (total 17 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   ID                        2073 non-null   int64
 1   Name                      2073 non-null   object
 2   Age                       2073 non-null   int64
 3   Nationality               2073 non-null   object
 4   Overall                   2073 non-null   int64
 5   Club                      2073 non-null   object
 6   Value                     2073 non-null   float64
 7   Wage                      2073 non-null   int64
 8   Preferred Foot            2073 non-null   object
 9   International Reputation  2073 non-null   float64
 10  Skill Moves               2073 non-null   float64
 11  Position                  2073 non-null   object
 12  Joined                    2073 non-null   int64
 13  Contract Valid Until      2073 non-null   object
 14  Height                    2073 non-null   float64
 15  Weight                    2073 non-null   float64
 16  Release Clause            2073 non-null   float64
dtypes: float64(6), int64(5), object(6)
memory usage: 275.4+ KB

**3. Напишите функцию, которая добавит колонку с разбиением возраста по группам: до 20, от 20 до 30, от 30 до
36 и старше 36. Посчитайте количество футболистов в каждой категории.**

In [64]:
def age_group(age_int):
    if age_int<=19:
      return 'До 20 лет'
    if 20<age_int<=30:
      return 'С 20 до 30 лет'
    if 30<age_int<=36:
      return 'С 30 до 36 лет'
    else:
      return 'Старше 36 лет'

In [65]:
df_new['Age_group'] = df_new['Age'].apply(age_group)

In [66]:
df_new['Age_group'].value_counts()

Age_group
С 20 до 30 лет    1391
С 30 до 36 лет     280
До 20 лет          262
Старше 36 лет      140
Name: count, dtype: int64